const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const bugsRouter = require('./routes/bugs');
const errorHandler = require('./middleware/errorHandler');
const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use('/api/bugs', bugsRouter);
app.use(errorHandler);
module.exports = app;